// Auto-generated by map_editor/app.py. Do not edit directly.
    wobj_clear(WNPC_MERCHANT);
    world.type[WNPC_MERCHANT] = WTYPE_ACTOR;
    world.flags[WNPC_MERCHANT] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WNPC_MERCHANT] = TILE_NPC_MERCHANT;
    world.x[WNPC_MERCHANT] = 10;
    world.y[WNPC_MERCHANT] = 6;
    wobj_add_child(WROOM_TOWN, WNPC_MERCHANT);

    wobj_clear(WITEM_FISH);
    world.type[WITEM_FISH] = WTYPE_ITEM;
    world.flags[WITEM_FISH] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WITEM_FISH] = TILE_ITEM_FISH;
    world.x[WITEM_FISH] = 12;
    world.y[WITEM_FISH] = 6;
    wobj_add_child(WROOM_TOWN, WITEM_FISH);

    wobj_clear(WNPC_LITTLE_GIRL);
    world.type[WNPC_LITTLE_GIRL] = WTYPE_ACTOR;
    world.flags[WNPC_LITTLE_GIRL] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_LITTLE_GIRL] = TILE_NPC_LITTLE_GIRL;
    world.x[WNPC_LITTLE_GIRL] = 6;
    world.y[WNPC_LITTLE_GIRL] = 6;
    wobj_add_child(WROOM_FOREST, WNPC_LITTLE_GIRL);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_WEREWOLF;
    world.x[WNPC_NEW] = 12;
    world.y[WNPC_NEW] = 7;
    wobj_add_child(WROOM_FOREST, WNPC_NEW);

    wobj_clear(WBOSS_OGRE);
    world.type[WBOSS_OGRE] = WTYPE_BOSS;
    world.flags[WBOSS_OGRE] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WBOSS_OGRE] = TILE_BOSS_OGRE;
    world.x[WBOSS_OGRE] = 9;
    world.y[WBOSS_OGRE] = 6;
    wobj_add_child(WROOM_OGRE_LAIR, WBOSS_OGRE);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_NEW] = TILE_NPC_OLD_MAN;
    world.x[WNPC_NEW] = 10;
    world.y[WNPC_NEW] = 2;
    wobj_add_child(WROOM_OGRE_LAIR, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WNPC_NEW] = TILE_NPC_KING;
    world.x[WNPC_NEW] = 12;
    world.y[WNPC_NEW] = 5;
    wobj_add_child(WROOM_CASTLE, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WNPC_NEW] = TILE_SILVER_KNIGHT;
    world.x[WNPC_NEW] = 10;
    world.y[WNPC_NEW] = 12;
    wobj_add_child(WROOM_CASTLE, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_SKELETON;
    world.x[WNPC_NEW] = 9;
    world.y[WNPC_NEW] = 9;
    wobj_add_child(WROOM_CRYPT, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_NEW] = TILE_NPC_CARPENTER;
    world.x[WNPC_NEW] = 10;
    world.y[WNPC_NEW] = 5;
    wobj_add_child(WROOM_CRYPT, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_GENIE;
    world.x[WNPC_NEW] = 9;
    world.y[WNPC_NEW] = 9;
    wobj_add_child(WROOM_TOWER, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_NEW] = TILE_NPC_MOTHER;
    world.x[WNPC_NEW] = 9;
    world.y[WNPC_NEW] = 4;
    wobj_add_child(WROOM_TOWER, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_ORC;
    world.x[WNPC_NEW] = 9;
    world.y[WNPC_NEW] = 6;
    wobj_add_child(WROOM_CAVE, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_NEW] = TILE_NPC_FATHER;
    world.x[WNPC_NEW] = 9;
    world.y[WNPC_NEW] = 3;
    wobj_add_child(WROOM_CAVE, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_TROLL;
    world.x[WNPC_NEW] = 10;
    world.y[WNPC_NEW] = 7;
    wobj_add_child(WROOM_RUINS, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_GHOST;
    world.x[WNPC_NEW] = 9;
    world.y[WNPC_NEW] = 7;
    wobj_add_child(WROOM_SHRINE, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_NEW] = TILE_NPC_OLD_MAN;
    world.x[WNPC_NEW] = 10;
    world.y[WNPC_NEW] = 5;
    wobj_add_child(WROOM_SHRINE, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_DARK_KNIGHT;
    world.x[WNPC_NEW] = 9;
    world.y[WNPC_NEW] = 6;
    wobj_add_child(WROOM_HARBOR, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WNPC_NEW] = TILE_ITEM_FISH;
    world.x[WNPC_NEW] = 9;
    world.y[WNPC_NEW] = 11;
    wobj_add_child(WROOM_HARBOR, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_BOSS_WIND_DRAGON;
    world.x[WNPC_NEW] = 7;
    world.y[WNPC_NEW] = 6;
    wobj_add_child(WROOM_MOUNTAIN_PASS, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_BOSS_FIRE_DRAGON;
    world.x[WNPC_NEW] = 9;
    world.y[WNPC_NEW] = 10;
    wobj_add_child(WROOM_VOLCANO, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_BOSS_WIND_DRAGON;
    world.x[WNPC_NEW] = 9;
    world.y[WNPC_NEW] = 6;
    wobj_add_child(WROOM_SKY_PEAK, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_BOSS_PUMPKIN_HEAD;
    world.x[WNPC_NEW] = 7;
    world.y[WNPC_NEW] = 7;
    wobj_add_child(WROOM_SWAMP, WNPC_NEW);

    wobj_clear(WNPC_NEW);
    world.type[WNPC_NEW] = WTYPE_ACTOR;
    world.flags[WNPC_NEW] = WFLAG_VISIBLE;
    world.sprite[WNPC_NEW] = TILE_COLOR_DEMONLORD;
    world.x[WNPC_NEW] = 8;
    world.y[WNPC_NEW] = 8;
    wobj_add_child(WROOM_DEMON_GATE, WNPC_NEW);

