// Auto-generated by map_editor/app.py. Do not edit directly.
    wobj_clear(WNPC_MERCHANT);
    world.type[WNPC_MERCHANT] = WTYPE_ACTOR;
    world.flags[WNPC_MERCHANT] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WNPC_MERCHANT] = TILE_NPC_MERCHANT;
    world.x[WNPC_MERCHANT] = 10;
    world.y[WNPC_MERCHANT] = 6;
    wobj_add_child(WROOM_TOWN, WNPC_MERCHANT);

    wobj_clear(WITEM_FISH);
    world.type[WITEM_FISH] = WTYPE_ITEM;
    world.flags[WITEM_FISH] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WITEM_FISH] = TILE_ITEM_FISH;
    world.x[WITEM_FISH] = 9;
    world.y[WITEM_FISH] = 6;
    wobj_add_child(WROOM_TOWN, WITEM_FISH);

    wobj_clear(WNPC_LITTLE_GIRL);
    world.type[WNPC_LITTLE_GIRL] = WTYPE_ACTOR;
    world.flags[WNPC_LITTLE_GIRL] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_LITTLE_GIRL] = TILE_NPC_LITTLE_GIRL;
    world.x[WNPC_LITTLE_GIRL] = 6;
    world.y[WNPC_LITTLE_GIRL] = 6;
    wobj_add_child(WROOM_FOREST, WNPC_LITTLE_GIRL);

    wobj_clear(WENT_WEREWOLF);
    world.type[WENT_WEREWOLF] = WTYPE_ACTOR;
    world.flags[WENT_WEREWOLF] = WFLAG_VISIBLE;
    world.sprite[WENT_WEREWOLF] = TILE_WEREWOLF;
    world.x[WENT_WEREWOLF] = 12;
    world.y[WENT_WEREWOLF] = 7;
    wobj_add_child(WROOM_FOREST, WENT_WEREWOLF);

    wobj_clear(WBOSS_OGRE);
    world.type[WBOSS_OGRE] = WTYPE_BOSS;
    world.flags[WBOSS_OGRE] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WBOSS_OGRE] = TILE_BOSS_OGRE;
    world.x[WBOSS_OGRE] = 9;
    world.y[WBOSS_OGRE] = 6;
    wobj_add_child(WROOM_OGRE_LAIR, WBOSS_OGRE);

    wobj_clear(WNPC_OLD_MAN);
    world.type[WNPC_OLD_MAN] = WTYPE_ACTOR;
    world.flags[WNPC_OLD_MAN] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_OLD_MAN] = TILE_NPC_OLD_MAN;
    world.x[WNPC_OLD_MAN] = 10;
    world.y[WNPC_OLD_MAN] = 2;
    wobj_add_child(WROOM_OGRE_LAIR, WNPC_OLD_MAN);

    wobj_clear(WNPC_KING);
    world.type[WNPC_KING] = WTYPE_ACTOR;
    world.flags[WNPC_KING] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WNPC_KING] = TILE_NPC_KING;
    world.x[WNPC_KING] = 12;
    world.y[WNPC_KING] = 5;
    wobj_add_child(WROOM_CASTLE, WNPC_KING);

    wobj_clear(WENT_SILVER_KNIGHT);
    world.type[WENT_SILVER_KNIGHT] = WTYPE_ACTOR;
    world.flags[WENT_SILVER_KNIGHT] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WENT_SILVER_KNIGHT] = TILE_SILVER_KNIGHT;
    world.x[WENT_SILVER_KNIGHT] = 10;
    world.y[WENT_SILVER_KNIGHT] = 12;
    wobj_add_child(WROOM_CASTLE, WENT_SILVER_KNIGHT);

    wobj_clear(WENT_SKELETON);
    world.type[WENT_SKELETON] = WTYPE_ACTOR;
    world.flags[WENT_SKELETON] = WFLAG_VISIBLE;
    world.sprite[WENT_SKELETON] = TILE_SKELETON;
    world.x[WENT_SKELETON] = 9;
    world.y[WENT_SKELETON] = 9;
    wobj_add_child(WROOM_CRYPT, WENT_SKELETON);

    wobj_clear(WNPC_CARPENTER);
    world.type[WNPC_CARPENTER] = WTYPE_ACTOR;
    world.flags[WNPC_CARPENTER] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_CARPENTER] = TILE_NPC_CARPENTER;
    world.x[WNPC_CARPENTER] = 10;
    world.y[WNPC_CARPENTER] = 5;
    wobj_add_child(WROOM_CRYPT, WNPC_CARPENTER);

    wobj_clear(WENT_GENIE);
    world.type[WENT_GENIE] = WTYPE_ACTOR;
    world.flags[WENT_GENIE] = WFLAG_VISIBLE;
    world.sprite[WENT_GENIE] = TILE_GENIE;
    world.x[WENT_GENIE] = 9;
    world.y[WENT_GENIE] = 9;
    wobj_add_child(WROOM_TOWER, WENT_GENIE);

    wobj_clear(WNPC_MOTHER);
    world.type[WNPC_MOTHER] = WTYPE_ACTOR;
    world.flags[WNPC_MOTHER] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_MOTHER] = TILE_NPC_MOTHER;
    world.x[WNPC_MOTHER] = 9;
    world.y[WNPC_MOTHER] = 4;
    wobj_add_child(WROOM_TOWER, WNPC_MOTHER);

    wobj_clear(WENT_ORC);
    world.type[WENT_ORC] = WTYPE_ACTOR;
    world.flags[WENT_ORC] = WFLAG_VISIBLE;
    world.sprite[WENT_ORC] = TILE_ORC;
    world.x[WENT_ORC] = 9;
    world.y[WENT_ORC] = 6;
    wobj_add_child(WROOM_CAVE, WENT_ORC);

    wobj_clear(WNPC_FATHER);
    world.type[WNPC_FATHER] = WTYPE_ACTOR;
    world.flags[WNPC_FATHER] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_FATHER] = TILE_NPC_FATHER;
    world.x[WNPC_FATHER] = 9;
    world.y[WNPC_FATHER] = 3;
    wobj_add_child(WROOM_CAVE, WNPC_FATHER);

    wobj_clear(WENT_TROLL);
    world.type[WENT_TROLL] = WTYPE_ACTOR;
    world.flags[WENT_TROLL] = WFLAG_VISIBLE;
    world.sprite[WENT_TROLL] = TILE_TROLL;
    world.x[WENT_TROLL] = 10;
    world.y[WENT_TROLL] = 7;
    wobj_add_child(WROOM_RUINS, WENT_TROLL);

    wobj_clear(WENT_GHOST);
    world.type[WENT_GHOST] = WTYPE_ACTOR;
    world.flags[WENT_GHOST] = WFLAG_VISIBLE;
    world.sprite[WENT_GHOST] = TILE_GHOST;
    world.x[WENT_GHOST] = 9;
    world.y[WENT_GHOST] = 7;
    wobj_add_child(WROOM_SHRINE, WENT_GHOST);

    wobj_clear(WNPC_OLD_MAN);
    world.type[WNPC_OLD_MAN] = WTYPE_ACTOR;
    world.flags[WNPC_OLD_MAN] = WFLAG_VISIBLE | WFLAG_INTERACTABLE | WFLAG_CAPTIVE;
    world.sprite[WNPC_OLD_MAN] = TILE_NPC_OLD_MAN;
    world.x[WNPC_OLD_MAN] = 10;
    world.y[WNPC_OLD_MAN] = 5;
    wobj_add_child(WROOM_SHRINE, WNPC_OLD_MAN);

    wobj_clear(WENT_DARK_KNIGHT);
    world.type[WENT_DARK_KNIGHT] = WTYPE_ACTOR;
    world.flags[WENT_DARK_KNIGHT] = WFLAG_VISIBLE;
    world.sprite[WENT_DARK_KNIGHT] = TILE_DARK_KNIGHT;
    world.x[WENT_DARK_KNIGHT] = 9;
    world.y[WENT_DARK_KNIGHT] = 6;
    wobj_add_child(WROOM_HARBOR, WENT_DARK_KNIGHT);

    wobj_clear(WITEM_FISH);
    world.type[WITEM_FISH] = WTYPE_ACTOR;
    world.flags[WITEM_FISH] = WFLAG_VISIBLE | WFLAG_INTERACTABLE;
    world.sprite[WITEM_FISH] = TILE_ITEM_FISH;
    world.x[WITEM_FISH] = 9;
    world.y[WITEM_FISH] = 11;
    wobj_add_child(WROOM_HARBOR, WITEM_FISH);

    wobj_clear(WBOSS_LAND_DRAGON);
    world.type[WBOSS_LAND_DRAGON] = WTYPE_BOSS;
    world.flags[WBOSS_LAND_DRAGON] = WFLAG_VISIBLE;
    world.sprite[WBOSS_LAND_DRAGON] = TILE_BOSS_LAND_DRAGON;
    world.x[WBOSS_LAND_DRAGON] = 7;
    world.y[WBOSS_LAND_DRAGON] = 6;
    wobj_add_child(WROOM_MOUNTAIN_PASS, WBOSS_LAND_DRAGON);

    wobj_clear(WBOSS_FIRE_DRAGON);
    world.type[WBOSS_FIRE_DRAGON] = WTYPE_BOSS;
    world.flags[WBOSS_FIRE_DRAGON] = WFLAG_VISIBLE;
    world.sprite[WBOSS_FIRE_DRAGON] = TILE_BOSS_FIRE_DRAGON;
    world.x[WBOSS_FIRE_DRAGON] = 9;
    world.y[WBOSS_FIRE_DRAGON] = 10;
    wobj_add_child(WROOM_VOLCANO, WBOSS_FIRE_DRAGON);

    wobj_clear(WBOSS_WIND_DRAGON);
    world.type[WBOSS_WIND_DRAGON] = WTYPE_BOSS;
    world.flags[WBOSS_WIND_DRAGON] = WFLAG_VISIBLE;
    world.sprite[WBOSS_WIND_DRAGON] = TILE_BOSS_WIND_DRAGON;
    world.x[WBOSS_WIND_DRAGON] = 9;
    world.y[WBOSS_WIND_DRAGON] = 6;
    wobj_add_child(WROOM_SKY_PEAK, WBOSS_WIND_DRAGON);

    wobj_clear(WBOSS_PUMPKIN_HEAD);
    world.type[WBOSS_PUMPKIN_HEAD] = WTYPE_BOSS;
    world.flags[WBOSS_PUMPKIN_HEAD] = WFLAG_VISIBLE;
    world.sprite[WBOSS_PUMPKIN_HEAD] = TILE_BOSS_PUMPKIN_HEAD;
    world.x[WBOSS_PUMPKIN_HEAD] = 7;
    world.y[WBOSS_PUMPKIN_HEAD] = 7;
    wobj_add_child(WROOM_SWAMP, WBOSS_PUMPKIN_HEAD);

    wobj_clear(WDEMONLORD);
    world.type[WDEMONLORD] = WTYPE_BOSS;
    world.flags[WDEMONLORD] = WFLAG_VISIBLE;
    world.sprite[WDEMONLORD] = TILE_COLOR_DEMONLORD;
    world.x[WDEMONLORD] = 8;
    world.y[WDEMONLORD] = 8;
    wobj_add_child(WROOM_DEMON_GATE, WDEMONLORD);

